version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of workflow files
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "ministryofjustice/hmpps-github-actions/*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: "docker"
    directory: "/images/java/distroless"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/images/java/eclipse-temurin"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/images/node/alpine"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/images/node/alpine-runtime"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/images/node/distroless"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/images/python/alpine"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
